export default  [
    {
        id: 0,
        img:"/p1.jpg",
        name: "Wild Silk Finish Lipstick",
        category: ["lipsticks"],
        sale: false,
        price: 10,
    },
    {
        id: 1,
        img:"/p24.jpg",
        name: "Wild Storm Skin Care",
        category: ["skin care"],
        sale: false,
        price: 15,
    },
    {
        id: 2,
        img:"/p25.jpg",
        name: "Wild Silk Cream",
        category: ["makeup"],
        sale: false,
        price: 80,
    },
    {
        id: 3,
        img:"/p7.jpg",
        name: "Wild Silk Nail Paint",
        category: ["nail"],
        sale: false,
        price: 10,
    },
    {
        id: 4,
        img:"/p17.jpg",
        name: "Wild Silk Nail Paint Black",
        category: ["nail"],
        sale: false,
        price: 25,
    },
    {
        id: 5,
        img:"/p3.jpg",
        name: "Wild Silk Finish Lipstick Green",
        category: ["lipsticks","makeup"],
        sale: true,
        price: 15,
    },
    {
        id: 6,
        img:"/p23.jpg",
        name: "Wild Storm Skin Care Oil",
        category: ["skin care"],
        sale: true,
        price: 100,
    },
    {
        id: 7,
        img:"/p11.jpg",
        name: "Wild Silk Contour Stick",
        category: ["makeup"],
        sale: false,
        price: 25,
    },
    {
        id: 8,
        img:"/p27.jpg",
        name: "Wild Storm Perfume",
        category: ["makeup"],
        sale: false,
        price: 25,
    },
]
